apiVersion: v1
kind: Pod
metadata:
  name: timlegge-general-use
spec:
  containers:
  - name: general-use
    image: gitlab-registry.nrp-nautilus.io/jmduarte/weaver:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: "2.5"
        memory: 16Gi
        nvidia.com/gpu: 1
      requests:
        cpu: "2.5"
        memory: 15Gi
        nvidia.com/gpu: 1
    volumeMounts:
    - name: part-vol-3
      mountPath: /part-vol-3/
  restartPolicy: Never
  volumes:
  - name: part-vol-3
    persistentVolumeClaim:
      claimName: part-vol-3
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
              - gpn-fiona-mizzou-2.rnet.missouri.edu
              - rci-nrp-gpu-05.sdsu.edu
              - node-2-2.sdsc.optiputer.net
