apiVersion: v1
kind: Pod
metadata:
  name: timlegge-qg-training-pod1
spec:
  containers:
  - name: qg-training
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hbb_interaction_network:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: "4"
        memory: 26Gi
        nvidia.com/gpu: 1
      requests:
        cpu: "4"
        memory: 22Gi
        nvidia.com/gpu: 1
    volumeMounts:
    - name: part-vol-3
      mountPath: /part-vol-3/tutorial-vol-legge
  restartPolicy: Never
  volumes:
  - name: part-vol-3
    persistentVolumeClaim:
      claimName: part-vol-3
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
              - gpn-fiona-mizzou-2.rnet.missouri.edu
              - rci-nrp-gpu-05.sdsu.edu
              - node-2-2.sdsc.optiputer.net
          - key: nvidia.com/gpu.product
            operator: In
            values:
              - NVIDIA-GeForce-RTX-1080
              - NVIDIA-GeForce-RTX-1080-Ti
              - NVIDIA-GeForce-RTX-2080-Ti
              - NVIDIA-GeForce-RTX-3080-Ti
